version: 2
jobs:
    build:
      docker:
        -image: ruby:2.4

      working_directory: /Users/Jay/ruby_apps/studio_game
      steps:
        - checkout
        - run: bundle install
        - run: rspec player_spec.rb
        - run: rspec game_spec.rb














