version: 2
jobs:
  build:
    working_directory: /Users/Jay/ruby_apps/studio_game
    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - checkout
      - run: bundle install
      - run: rspec player_spec.rb
      - run: rspec game_spec.rb


